spring.application.name=OnlineShopping
spring.data.mongodb.uri=mongodb://localhost:27017/travel_planner
# Tell Spring Boot where the database server is running
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017

# Explicitly force Spring Boot to use the travel_planner database
spring.data.mongodb.database=travel_planner
